Repository BackburnerJS/backburner.js, pull requests merged in 2021-04, with the labels that each got.

#383 Export types
  ember-cli-build.js
  lib/backburner/queue.ts
  lib/index.ts
  package.json
  tsconfig.json
Labels: enhancement

#390 Remove Downloads section from README
  README.md
Labels: documentation

#391 Add basic release automation setup.
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal
